# Generated by Django 3.1.7 on 2021-03-26 13:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=20, message='Не более 20 символов'), django.core.validators.MinLengthValidator(limit_value=3, message='не менее 3 символов')])),
                ('address', models.TextField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True, verbose_name='Название курса')),
                ('address', models.TextField(blank=True, max_length=128, null=True, verbose_name='Адрес')),
                ('price_per_month', models.IntegerField(verbose_name='Цена за месяц')),
                ('total_price', models.IntegerField(verbose_name='Полная цена за курс')),
                ('description', models.TextField(max_length=128, verbose_name='Описание курса')),
                ('image', models.ImageField(upload_to='media/courses_info', verbose_name='фотоязыкапрограммирования')),
                ('courses_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course', verbose_name='Курс')),
                ('programming_languages_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.programminglanguages', verbose_name='язык программирования')),
            ],
            options={
                'verbose_name': 'Информация о курсе',
                'verbose_name_plural': 'Информация о курсах',
            },
        ),
    ]
