# Generated by Django 3.1.7 on 2021-03-29 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguages',
            name='title',
            field=models.TextField(blank=True, max_length=64, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=30, message='Не более 30 символов'), django.core.validators.MinLengthValidator(limit_value=2, message='не менее 2 символов')]),
        ),
    ]
