# Generated by Django 3.1.7 on 2021-03-29 19:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20210329_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='continuance',
            field=models.IntegerField(default=1, verbose_name='Количество месяцев'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=35, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=35, message='Не более 20 символов'), django.core.validators.MinLengthValidator(limit_value=3, message='не менее 3 символов')]),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.TextField(max_length=2500, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='programminglanguages',
            name='title',
            field=models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=100, message='Не более 30 символов'), django.core.validators.MinLengthValidator(limit_value=2, message='не менее 2 символов')]),
        ),
        migrations.CreateModel(
            name='CourseSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('courseinfo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_signup', to='course.courseinfo', verbose_name='Информация о курсах')),
                ('price_per_month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.courseinfo', verbose_name='Цена за месяц')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Запись на курс',
                'verbose_name_plural': 'Запись на курсы',
            },
        ),
    ]
