# Generated by Django 3.1.7 on 2021-03-31 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20210331_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesignup',
            name='programming_languages_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.programminglanguages', verbose_name='языки программирования'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/course_info', verbose_name='фото языка программирования'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='title',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Название школы'),
        ),
        migrations.AlterField(
            model_name='coursesignup',
            name='courseinfo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_signup', to='course.courseinfo', verbose_name='Информация о курсах'),
        ),
    ]
