# Generated by Django 3.1.7 on 2021-03-31 13:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20210331_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='course_id',
            new_name='courses_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=15, message='Не более 15 символов'), django.core.validators.MinLengthValidator(limit_value=5, message='не менее 5 символов')]),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/courses_info', verbose_name='фотоязыкапрограммирования'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='coursesignup',
            name='courseinfo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_signup', to='course.courseinfo', verbose_name='Информация о курсах'),
        ),
    ]
