# Generated by Django 3.1.7 on 2021-03-31 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20210331_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='courses_id',
            new_name='course_id',
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='address',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='description',
            field=models.TextField(max_length=128, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/course_info', verbose_name='фото языка программирования'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Название курса'),
        ),
        migrations.AlterField(
            model_name='coursesignup',
            name='courseinfo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_signup', to='course.courseinfo', verbose_name='Информация о курсах'),
        ),
    ]
