# Generated by Django 3.1.7 on 2021-03-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20210331_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguages',
            name='title',
            field=models.TextField(max_length=64, null=True),
        ),
    ]
