# Generated by Django 3.1.7 on 2021-03-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_auto_20210331_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesignup',
            name='programming_languages_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.programminglanguages', verbose_name='языки программирования'),
        ),
    ]
